module.exports = [
    {
      "id": 1,
      "name": "Mikra Lumos",
      "nickname": "Silencer",
      "class": "Assault Infantry",
      "missions": 5,
      "shots": 28,
      "hits": 21,
      "kills": 22,
      "lost_kills": 12, 
      "damage_dealt": 122,
      "tiles_moved": 523,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 2,
      "name": "Antonin Akimov",
      "nickname": "ReaktorFour",
      "class": "Field Medic",
      "missions": 6,
      "shots": 27,
      "hits": 22,
      "kills": 19,
      "lost_kills": 9,
      "damage_dealt": 106,
      "tiles_moved": 565,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 3,
      "name": "Syn Doriel",
      "nickname": "Zenith",
      "class": "Field Medic",
      "missions": 3,
      "shots": 15,
      "hits": 11,
      "kills": 8,
      "lost_kills": 5,
      "damage_dealt": 46,
      "tiles_moved": 271,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 4,
      "name": "Boltos Degrir",
      "nickname": "Yggdrasil",
      "class": "Skirmisher",
      "missions": 8,
      "shots": 54,
      "hits": 37,
      "kills": 33,
      "lost_kills": 13,
      "damage_dealt": 251,
      "tiles_moved": 880,
      "dead": false,
      "mvps": 3
    },
    {
      "id": 5,
      "name": "Rhiannon Rasa",
      "nickname": "Tabula",
      "class": "Phalanx",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 5,
      "lost_kills": 3,
      "damage_dealt": 28,
      "tiles_moved": 218,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 6,
      "name": "Else Konig",
      "nickname": "Dynamite",
      "class": "Marksman",
      "missions": 10,
      "shots": 68,
      "hits": 59,
      "kills": 42,
      "lost_kills": 25,
      "damage_dealt": 291,
      "tiles_moved": 782,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 7,
      "name": "Norman Harris",
      "nickname": "Waffleman",
      "class": "Rookie",
      "missions": 1,
      "shots": 2,
      "hits": 1,
      "kills": 1,
      "lost_kills": 1,
      "damage_dealt": 4,
      "tiles_moved": 31,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 8,
      "name": "Nicholas Cutter",
      "nickname": "Beardo",
      "class": "Sapper",
      "missions": 8,
      "shots": 50,
      "hits": 32,
      "kills": 32,
      "lost_kills": 16,
      "damage_dealt": 226,
      "tiles_moved": 776,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 9,
      "name": "Jackson Hopper",
      "nickname": "Stiggs",
      "class": "Phalanx",
      "missions": 2,
      "shots": 9,
      "hits": 7,
      "kills": 6,
      "lost_kills": 6,
      "damage_dealt": 28,
      "tiles_moved": 223,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 10,
      "name": "Rebecca Trell",
      "nickname": "Ghilan'nain",
      "class": "Marksman",
      "missions": 5,
      "shots": 19,
      "hits": 18,
      "kills": 10,
      "lost_kills": 4,
      "damage_dealt": 117,
      "tiles_moved": 395,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 11,
      "name": "Sara Triplett",
      "nickname": "Bumblebee",
      "class": "Field Medic",
      "missions": 7,
      "shots": 24,
      "hits": 16,
      "kills": 10,
      "lost_kills": 0,
      "damage_dealt": 66,
      "tiles_moved": 542,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 12,
      "name": "Adrienne Wong",
      "nickname": "Weathergirl",
      "class": "Combat Engineer",
      "missions": 8,
      "shots": 16,
      "hits": 11,
      "kills": 33,
      "lost_kills": 14,
      "damage_dealt": 238,
      "tiles_moved": 966,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 13,
      "name": "Jordan Nomir",
      "nickname": "Stone",
      "class": "Assault Infantry",
      "missions": 3,
      "shots": 8,
      "hits": 4,
      "kills": 3,
      "lost_kills": 0,
      "damage_dealt": 33,
      "tiles_moved": 223,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 14,
      "name": "Jamie Wilson",
      "nickname": "Angerbot",
      "class": "Tech Specialist",
      "missions": 6,
      "shots": 16,
      "hits": 11,
      "kills": 8,
      "lost_kills": 2,
      "damage_dealt": 68,
      "tiles_moved": 479,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 15,
      "name": "Zara Morlin",
      "nickname": "Poolmother",
      "class": "Keeper",
      "missions": 8,
      "shots": 62,
      "hits": 49,
      "kills": 30,
      "lost_kills": 18,
      "damage_dealt": 209,
      "tiles_moved": 867,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 16,
      "name": "Byron Powell",
      "nickname": "Night Wolf",
      "class": "Templar",
      "missions": 5,
      "shots": 5,
      "hits": 1,
      "kills": 13,
      "lost_kills": 0,
      "damage_dealt": 89,
      "tiles_moved": 507,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 17,
      "name": "Vanille Marchland",
      "nickname": "Pin'kPoint",
      "class": "Phalanx",
      "missions": 4,
      "shots": 20,
      "hits": 12,
      "kills": 11,
      "lost_kills": 5,
      "damage_dealt": 85,
      "tiles_moved": 453,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 18,
      "name": "Marcel Schmidt",
      "nickname": "Muhzn",
      "class": "Sapper",
      "missions": 7,
      "shots": 13,
      "hits": 5,
      "kills": 13,
      "lost_kills": 0,
      "damage_dealt": 109,
      "tiles_moved": 494,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 19,
      "name": "Nazara Mercer",
      "nickname": "Stargrave",
      "class": "Sapper",
      "missions": 4,
      "shots": 18,
      "hits": 13,
      "kills": 20,
      "lost_kills": 9,
      "damage_dealt": 121,
      "tiles_moved": 519,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 20,
      "name": "Temuulen Zaya",
      "nickname": "Serenity",
      "class": "Marine",
      "missions": 3,
      "shots": 13,
      "hits": 5,
      "kills":4,
      "lost_kills": 0,
      "damage_dealt": 46,
      "tiles_moved": 208,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 21,
      "name": "Clay Wolf",
      "nickname": "Six",
      "class": "Marine",
      "missions": 6,
      "shots": 50,
      "hits": 36,
      "kills": 20,
      "lost_kills": 12,
      "damage_dealt": 190,
      "tiles_moved": 463,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 22,
      "name": "Chasu Bao",
      "nickname": "Takeout",
      "class": "Combat Engineer",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 10,
      "lost_kills": 2,
      "damage_dealt": 84,
      "tiles_moved": 190,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 23,
      "name": "Emika Mikami",
      "nickname": "Red Dawn",
      "class": "Combat Engineer",
      "missions": 4,
      "shots": 7,
      "hits": 4,
      "kills": 10,
      "lost_kills": 2,
      "damage_dealt": 84,
      "tiles_moved": 369,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 24,
      "name": "Virtual Viking",
      "nickname": "Odin",
      "class": "Reaper",
      "missions": 3,
      "shots": 21,
      "hits": 19,
      "kills": 10,
      "lost_kills": 5,
      "damage_dealt": 87,
      "tiles_moved": 482,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 25,
      "name": "Nina Verducci",
      "nickname": "Sovereign",
      "class": "Rookie",
      "missions": 1,
      "shots": 3,
      "hits": 3,
      "kills": 2,
      "lost_kills": 0,
      "damage_dealt": 13,
      "tiles_moved": 99,
      "dead": true,
      "mvps": 1
    },
    {
      "id": 26,
      "name": "The Forgotten",
      "nickname": "FORT-E",
      "class": "Spark",
      "missions": 5,
      "shots": 14,
      "hits": 11,
      "kills": 22,
      "lost_kills": 0,
      "damage_dealt": 262,
      "tiles_moved": 380,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 27,
      "name": "Matt Brunton",
      "nickname": "Pale Rider",
      "class": "Assault Infantry",
      "missions": 3,
      "shots": 15,
      "hits": 14,
      "kills": 12,
      "lost_kills": 0,
      "damage_dealt": 111,
      "tiles_moved": 354,
      "dead": false,
      "mvps": 3
    },
    {
      "id": 28,
      "name": "Boulanger 42",
      "nickname": "Toaster",
      "class": "Spark",
      "missions": 5,
      "shots": 49,
      "hits": 36,
      "kills": 36,
      "lost_kills": 25,
      "damage_dealt": 355,
      "tiles_moved": 670,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 29,
      "name": "Keiden von Moffrichsen",
      "nickname": "RAiD",
      "class": "Marine",
      "missions": 2,
      "shots": 4,
      "hits": 4,
      "kills": 2,
      "lost_kills": 0,
      "damage_dealt": 27,
      "tiles_moved": 101,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 30,
      "name": "Rojoash of Ekertho",
      "nickname": "Alien",
      "class": "Combat Engineer",
      "missions": 1,
      "shots": 6,
      "hits": 2,
      "kills": 8,
      "lost_kills": 6, 
      "damage_dealt": 55,
      "tiles_moved": 109,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 31,
      "name": "Zoe Zachariah",
      "nickname": "Double Z",
      "class": "Tech Specialist",
      "missions": 2,
      "shots": 3,
      "hits": 2,
      "kills": 4,
      "lost_kills": 0, 
      "damage_dealt": 15,
      "tiles_moved": 145,
      "dead": false,
      "mvps": 0
    }
  ]

