module.exports = [
    {
      "id": 1,
      "name": "Mikra Lumos",
      "nickname": "Silencer",
      "class": "Assault Infantry",
      "missions": 5,
      "shots": 28,
      "hits": 21,
      "kills": 22,
      "lost_kills": 12, 
      "damage_dealt": 122,
      "tiles_moved": 523,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 2,
      "name": "Antonin Akimov",
      "nickname": "ReaktorFour",
      "class": "Field Medic",
      "missions": 5,
      "shots": 22,
      "hits": 17,
      "kills": 15,
      "lost_kills": 9,
      "damage_dealt": 82,
      "tiles_moved": 465,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 3,
      "name": "Syn Doriel",
      "nickname": "Zenith",
      "class": "Field Medic",
      "missions": 3,
      "shots": 15,
      "hits": 11,
      "kills": 8,
      "lost_kills": 5,
      "damage_dealt": 46,
      "tiles_moved": 271,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 4,
      "name": "Boltos Degrir",
      "nickname": "Yggdrasil",
      "class": "Skirmisher",
      "missions": 7,
      "shots": 38,
      "hits": 27,
      "kills": 25,
      "lost_kills": 13,
      "damage_dealt": 156,
      "tiles_moved": 582,
      "dead": false,
      "mvps": 3
    },
    {
      "id": 5,
      "name": "Rhiannon Rasa",
      "nickname": "Tabula",
      "class": "Phalanx",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 5,
      "lost_kills": 3,
      "damage_dealt": 28,
      "tiles_moved": 218,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 6,
      "name": "Else Konig",
      "nickname": "Dynamite",
      "class": "Marksman",
      "missions": 6,
      "shots": 50,
      "hits": 41,
      "kills": 31,
      "lost_kills": 25,
      "damage_dealt": 185,
      "tiles_moved": 584,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 7,
      "name": "Norman Harris",
      "nickname": "Waffleman",
      "class": "Rookie",
      "missions": 1,
      "shots": 2,
      "hits": 1,
      "kills": 1,
      "lost_kills": 1,
      "damage_dealt": 4,
      "tiles_moved": 21,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 8,
      "name": "Nicholas Cutter",
      "nickname": "Beardo",
      "class": "Sapper",
      "missions": 5,
      "shots": 26,
      "hits": 18,
      "kills": 16,
      "lost_kills": 9,
      "damage_dealt": 115,
      "tiles_moved": 459,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 9,
      "name": "Jackson Hopper",
      "nickname": "Stiggs",
      "class": "Phalanx",
      "missions": 2,
      "shots": 9,
      "hits": 7,
      "kills": 6,
      "lost_kills": 6,
      "damage_dealt": 28,
      "tiles_moved": 223,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 10,
      "name": "Rebecca Trell",
      "nickname": "Ghilan'nain",
      "class": "Marksman",
      "missions": 2,
      "shots": 2,
      "hits": 2,
      "kills": 0,
      "lost_kills": 0,
      "damage_dealt": 13,
      "tiles_moved": 168,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 11,
      "name": "Sara Triplett",
      "nickname": "Bumblebee",
      "class": "Field Medic",
      "missions": 4,
      "shots": 12,
      "hits": 8,
      "kills": 6,
      "damage_dealt": 33,
      "tiles_moved": 343,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 12,
      "name": "Adrienne Wong",
      "nickname": "Weathergirl",
      "class": "Combat Engineer",
      "missions": 6,
      "shots": 12,
      "hits": 7,
      "kills": 29,
      "lost_kills": 14,
      "damage_dealt": 200,
      "tiles_moved": 703,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 13,
      "name": "Jordan Nomir",
      "nickname": "Stone",
      "class": "Assault Infantry",
      "missions": 3,
      "shots": 8,
      "hits": 4,
      "kills": 3,
      "lost_kills": 0,
      "damage_dealt": 33,
      "tiles_moved": 223,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 14,
      "name": "Jamie Wilson",
      "nickname": "Angerbot",
      "class": "Tech Specialist",
      "missions": 3,
      "shots": 6,
      "hits": 3,
      "kills": 2,
      "lost_kills": 0,
      "damage_dealt": 12,
      "tiles_moved": 272,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 15,
      "name": "Zara Morlin",
      "nickname": "Poolmother",
      "class": "Keeper",
      "missions": 6,
      "shots": 43,
      "hits": 35,
      "kills": 25,
      "lost_kills": 18,
      "damage_dealt": 152,
      "tiles_moved": 529,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 16,
      "name": "Byron Powell",
      "nickname": "Night Wolf",
      "class": "Templar",
      "missions": 4,
      "shots": 5,
      "hits": 1,
      "kills": 12,
      "lost_kills": 0,
      "damage_dealt": 86,
      "tiles_moved": 507,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 17,
      "name": "Vanille Marchland",
      "nickname": "Pin'kPoint",
      "class": "Phalanx",
      "missions": 4,
      "shots": 13,
      "hits": 8,
      "kills": 7,
      "lost_kills": 5,
      "damage_dealt": 36,
      "tiles_moved": 414,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 18,
      "name": "Marcel Schmidt",
      "nickname": "Muhzn",
      "class": "Sapper",
      "missions": 4,
      "shots": 9,
      "hits": 3,
      "kills": 11,
      "lost_kills": 0,
      "damage_dealt": 68,
      "tiles_moved": 378,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 19,
      "name": "Nazara Mercer",
      "nickname": "Stargrave",
      "class": "Sapper",
      "missions": 2,
      "shots": 9,
      "hits": 7,
      "kills": 11,
      "lost_kills": 9,
      "damage_dealt": 58,
      "tiles_moved": 487,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 20,
      "name": "Temuulen Zaya",
      "nickname": "Serenity",
      "class": "Marine",
      "missions": 1,
      "shots": 3,
      "hits": 0,
      "kills": 0,
      "lost_kills": 0,
      "damage_dealt": 0,
      "tiles_moved": 150,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 21,
      "name": "Clay Wolf",
      "nickname": "Six",
      "class": "Marine",
      "missions": 2,
      "shots": 24,
      "hits": 18,
      "kills": 15,
      "lost_kills": 12,
      "damage_dealt": 98,
      "tiles_moved": 349,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 22,
      "name": "Chasu Bao",
      "nickname": "Takeout",
      "class": "Combat Engineer",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 10,
      "lost_kills": 2,
      "damage_dealt": 84,
      "tiles_moved": 78,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 23,
      "name": "Emika Mikami",
      "nickname": "Red Dawn",
      "class": "Combat Engineer",
      "missions": 3,
      "shots": 4,
      "hits": 3,
      "kills": 7,
      "lost_kills": 2,
      "damage_dealt": 54,
      "tiles_moved": 236,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 24,
      "name": "Virtual Viking",
      "nickname": "Odin",
      "class": "Reaper",
      "missions": 2,
      "shots": 9,
      "hits": 8,
      "kills": 6,
      "lost_kills": 0,
      "damage_dealt": 31,
      "tiles_moved": 306,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 25,
      "name": "Nina Verducci",
      "nickname": "Sovereign",
      "class": "Rookie",
      "missions": 1,
      "shots": 3,
      "hits": 3,
      "kills": 2,
      "lost_kills": 0,
      "damage_dealt": 13,
      "tiles_moved": 99,
      "dead": true,
      "mvps": 1
    },
    {
      "id": 26,
      "name": "The Forgotten",
      "nickname": "FORT-E",
      "class": "Spark",
      "missions": 1,
      "shots": 3,
      "hits": 2,
      "kills": 3,
      "damage_dealt": 35,
      "tiles_moved": 0,
      "dead": false,
      "mvps": 0
    }
  ]

