module.exports = [
    {
      "id": 1,
      "name": "Mikra Lumos",
      "nickname": "Silencer",
      "class": "Assault Infantry",
      "missions": 5,
      "shots": 28,
      "hits": 21,
      "kills": 22,
      "lost_kills": 12, 
      "damage_dealt": 122,
      "tiles_moved": 523,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 2,
      "name": "Antonin Akimov",
      "nickname": "ReaktorFour",
      "class": "Field Medic",
      "missions": 8,
      "shots": 36,
      "hits": 27,
      "kills": 22,
      "lost_kills": 9,
      "damage_dealt": 128,
      "tiles_moved": 806,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 3,
      "name": "Syn Doriel",
      "nickname": "Zenith",
      "class": "Field Medic",
      "missions": 3,
      "shots": 15,
      "hits": 11,
      "kills": 8,
      "lost_kills": 5,
      "damage_dealt": 46,
      "tiles_moved": 271,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 4,
      "name": "Boltos Degrir",
      "nickname": "Yggdrasil",
      "class": "Skirmisher",
      "missions": 9,
      "shots": 86,
      "hits": 63,
      "kills": 51,
      "lost_kills": 13,
      "damage_dealt": 477,
      "tiles_moved": 1356,
      "dead": false,
      "mvps": 5
    },
    {
      "id": 5,
      "name": "Rhiannon Rasa",
      "nickname": "Tabula",
      "class": "Phalanx",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 5,
      "lost_kills": 3,
      "damage_dealt": 28,
      "tiles_moved": 218,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 6,
      "name": "Else Konig",
      "nickname": "Dynamite",
      "class": "Marksman",
      "missions": 11,
      "shots": 91,
      "hits": 80,
      "kills": 48,
      "lost_kills": 25,
      "damage_dealt": 422,
      "tiles_moved": 884,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 7,
      "name": "Norman Harris",
      "nickname": "Waffleman",
      "class": "Rookie",
      "missions": 1,
      "shots": 2,
      "hits": 1,
      "kills": 1,
      "lost_kills": 1,
      "damage_dealt": 4,
      "tiles_moved": 31,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 8,
      "name": "Nicholas Cutter",
      "nickname": "Beardo",
      "class": "Sapper",
      "missions": 10,
      "shots": 64,
      "hits": 40,
      "kills": 37,
      "lost_kills": 16,
      "damage_dealt": 308,
      "tiles_moved": 1118,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 9,
      "name": "Jackson Hopper",
      "nickname": "Stiggs",
      "class": "Phalanx",
      "missions": 3,
      "shots": 12,
      "hits": 8,
      "kills": 7,
      "lost_kills": 6,
      "damage_dealt": 34,
      "tiles_moved": 328,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 10,
      "name": "Rebecca Trell",
      "nickname": "Ghilan'nain",
      "class": "Marksman",
      "missions": 8,
      "shots": 54,
      "hits": 50,
      "kills": 27,
      "lost_kills": 4,
      "damage_dealt": 300,
      "tiles_moved": 810,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 11,
      "name": "Sara Triplett",
      "nickname": "Bumblebee",
      "class": "Field Medic",
      "missions": 9,
      "shots": 34,
      "hits": 21,
      "kills": 13,
      "lost_kills": 0,
      "damage_dealt": 99,
      "tiles_moved": 766,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 12,
      "name": "Adrienne Wong",
      "nickname": "Weathergirl",
      "class": "Combat Engineer",
      "missions": 10,
      "shots": 27,
      "hits": 19,
      "kills": 39,
      "lost_kills": 14,
      "damage_dealt": 323,
      "tiles_moved": 1187,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 13,
      "name": "Jordan Nomir",
      "nickname": "Stone",
      "class": "Assault Infantry",
      "missions": 3,
      "shots": 8,
      "hits": 4,
      "kills": 3,
      "lost_kills": 0,
      "damage_dealt": 33,
      "tiles_moved": 223,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 14,
      "name": "Jamie Wilson",
      "nickname": "Angerbot",
      "class": "Tech Specialist",
      "missions": 7,
      "shots": 25,
      "hits": 19,
      "kills": 12,
      "lost_kills": 2,
      "damage_dealt": 120,
      "tiles_moved": 647,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 15,
      "name": "Zara Morlin",
      "nickname": "Poolmother",
      "class": "Keeper",
      "missions": 10,
      "shots": 77,
      "hits": 61,
      "kills": 34,
      "lost_kills": 18,
      "damage_dealt": 265,
      "tiles_moved": 1092,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 16,
      "name": "Byron Powell",
      "nickname": "Night Wolf",
      "class": "Templar",
      "missions": 7,
      "shots": 9,
      "hits": 5,
      "kills": 13,
      "lost_kills": 0,
      "damage_dealt": 179,
      "tiles_moved": 863,
      "dead": false,
      "mvps": 3
    },
    {
      "id": 17,
      "name": "Vanille Marchland",
      "nickname": "Pin'kPoint",
      "class": "Phalanx",
      "missions": 5,
      "shots": 25,
      "hits": 16,
      "kills": 13,
      "lost_kills": 5,
      "damage_dealt": 92,
      "tiles_moved": 596,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 18,
      "name": "Marcel Schmidt",
      "nickname": "Muhzn",
      "class": "Sapper",
      "missions": 9,
      "shots": 27,
      "hits": 22,
      "kills": 22,
      "lost_kills": 0,
      "damage_dealt": 210,
      "tiles_moved": 829,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 19,
      "name": "Nazara Mercer",
      "nickname": "Stargrave",
      "class": "Sapper",
      "missions": 6,
      "shots": 33,
      "hits": 22,
      "kills": 26,
      "lost_kills": 9,
      "damage_dealt": 237,
      "tiles_moved": 752,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 20,
      "name": "Temuulen Zaya",
      "nickname": "Serenity",
      "class": "Marine",
      "missions": 5,
      "shots": 39,
      "hits": 23,
      "kills": 12,
      "lost_kills": 0,
      "damage_dealt": 162,
      "tiles_moved": 377,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 21,
      "name": "Clay Wolf",
      "nickname": "Six",
      "class": "Marine",
      "missions": 8,
      "shots": 80,
      "hits": 54,
      "kills": 31,
      "lost_kills": 12,
      "damage_dealt": 307,
      "tiles_moved": 632,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 22,
      "name": "Chasu Bao",
      "nickname": "Takeout",
      "class": "Combat Engineer",
      "missions": 2,
      "shots": 5,
      "hits": 3,
      "kills": 10,
      "lost_kills": 2,
      "damage_dealt": 84,
      "tiles_moved": 190,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 23,
      "name": "Emika Mikami",
      "nickname": "Red Dawn",
      "class": "Combat Engineer",
      "missions": 4,
      "shots": 7,
      "hits": 4,
      "kills": 10,
      "lost_kills": 2,
      "damage_dealt": 84,
      "tiles_moved": 369,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 24,
      "name": "Virtual Viking",
      "nickname": "Odin",
      "class": "Reaper",
      "missions": 4,
      "shots": 35,
      "hits": 28,
      "kills": 18,
      "lost_kills": 5,
      "damage_dealt": 121,
      "tiles_moved": 870,
      "dead": false,
      "mvps": 1
    },
    {
      "id": 25,
      "name": "Nina Verducci",
      "nickname": "Sovereign",
      "class": "Rookie",
      "missions": 1,
      "shots": 3,
      "hits": 3,
      "kills": 2,
      "lost_kills": 0,
      "damage_dealt": 13,
      "tiles_moved": 99,
      "dead": true,
      "mvps": 1
    },
    {
      "id": 26,
      "name": "The Forgotten",
      "nickname": "FORT-E",
      "class": "Spark",
      "missions": 5,
      "shots": 14,
      "hits": 11,
      "kills": 22,
      "lost_kills": 0,
      "damage_dealt": 262,
      "tiles_moved": 380,
      "dead": true,
      "mvps": 2
    },
    {
      "id": 27,
      "name": "Matt Brunton",
      "nickname": "Pale Rider",
      "class": "Assault Infantry",
      "missions": 4,
      "shots": 19,
      "hits": 17,
      "kills": 17,
      "lost_kills": 0,
      "damage_dealt": 148,
      "tiles_moved": 528,
      "dead": false,
      "mvps": 4
    },
    {
      "id": 28,
      "name": "Boulanger 42",
      "nickname": "Toaster",
      "class": "Spark",
      "missions": 7,
      "shots": 68,
      "hits": 51,
      "kills": 46,
      "lost_kills": 25,
      "damage_dealt": 508,
      "tiles_moved": 1225,
      "dead": false,
      "mvps": 2
    },
    {
      "id": 29,
      "name": "Keiden von Moffrichsen",
      "nickname": "RAiD",
      "class": "Marine",
      "missions": 3,
      "shots": 8,
      "hits": 7,
      "kills": 4,
      "lost_kills": 0,
      "damage_dealt": 61,
      "tiles_moved": 165,
      "dead": true,
      "mvps": 0
    },
    {
      "id": 30,
      "name": "Rojoash of Ekertho",
      "nickname": "Alien",
      "class": "Combat Engineer",
      "missions": 2,
      "shots": 11,
      "hits": 6,
      "kills": 10,
      "lost_kills": 6, 
      "damage_dealt": 96,
      "tiles_moved": 194,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 31,
      "name": "Zoe Zachariah",
      "nickname": "Double Z",
      "class": "Tech Specialist",
      "missions": 3,
      "shots": 8,
      "hits": 5,
      "kills": 7,
      "lost_kills": 0, 
      "damage_dealt": 40,
      "tiles_moved": 407,
      "dead": false,
      "mvps": 0
    },
    {
      "id": 32,
      "name": "Yverose Baptiste",
      "nickname": "Buzzkill",
      "class": "SPARK",
      "missions": 2,
      "shots": 5,
      "hits": 4,
      "kills": 15,
      "lost_kills": 0, 
      "damage_dealt": 231,
      "tiles_moved": 120,
      "dead": false,
      "mvps": 0
    }
  ]

